#!/bin/bash

# Exit immediately on errors, and echo commands as they are executed.
set -e

#
# Defines some global variables for colors.
# Forked from https://github.com/colorful-tones/newsite/
#
normal=$(tput sgr0)
bold=$(tput bold)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
black=$(tput setaf 7)
# Copy the mu-plugins loader file.
rsync vendor/pantheon-systems/pantheon-wp-loader/loader.php web/wp-content/mu-plugins/

rsync vendor/pantheon-systems/wordpress-integrations/pantheon.upstream.yml web/wp/

# Copy over the mu-plugins folder from core wp, if it exists.
if [ -d "web/wp/wp-content/mu-plugins/" ]; then
  rsync -r web/wp/wp-content/mu-plugins/* web/wp-content/mu-plugins/
fi

# Delete the core wp-config file, if it exists.
if [ -f "web/wp/wp-config.php" ]; then
  rm web/wp/wp-config.php
fi

# Remove the wp-content directory from core WordPress.
if [ -d "web/wp/wp-content" ]; then
  rm -rf web/wp/wp-content
fi
